version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: shopping-jewel-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: shopping_cart
      MYSQL_USER: shopuser
      MYSQL_PASSWORD: shoppass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-pshoppass"]
      interval: 10s
      timeout: 5s
      retries: 10

  smtp:
    image: maildev/maildev
    container_name: shopping-jewel-smtp
    ports:
      - 1080:1080
      - 1025:1025
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1025"]
      interval: 5s
      timeout: 5s
      retries: 5	  

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: shopping-jewel-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shopping_cart?createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: shopuser
      SPRING_DATASOURCE_PASSWORD: shoppass
      JWT_SECRET: 3txBv4w/zqWBKY5zHHT7p4kx547vqixR/yH5jUTHScY=
      SPRING_MAIL_HOST: smtp
      SPRING_MAIL_PORT: 1025
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    container_name: shopping-jewel-frontend
    restart: always
    ports:
      - 3000:80
    depends_on:
      backend:
        condition: service_healthy

volumes:
  mysql_data:
